try{
    let a;
    console.log(a.length);
    console.log("Hi there from inside");
}catch(error){
    console.log("Something went wrong");
}

console.log("Hi, there");